import styles from "./page.module.scss";

export const metadata = {
  title: "About page",
  description: "Generated by create next app",
};

export default function AboutLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <div className={styles.header}>
        <h1>About Header</h1>
      </div>
      {children}
      <div className={styles.header}>
        <h1>About Footer</h1>
      </div>
    </>
  );
}
