import "./globals.scss";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
import styles from "./page.module.scss";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "My new Nextjs app",
  description: "Generated by create next app",
};

//EVERYTHING IN THE MAIN LAYOUT FILE IS APPLIED TO THE WHOLE WEBSITE

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* APPLY THE FONT FOR THE WHOLE WEBSITE HERE */}
      <body className={inter.className}>
        <div className={styles.header}>
          <h1>Header</h1>
        </div>
        {children}
        <div className={styles.header}>
          <h1>Footer</h1>
        </div>
      </body>
    </html>
  );
}
